ArrayStack:
	g++ -o ArrayStack.o Stack.h ArrayStack.cpp

DoubleArray:
	g++ -o DoubleArrayStack.o Stack.h DoubleArrayStack.cpp

LinkList:
	g++ -o LinkListStack.o Stack.h LinkListStack.cpp


.PHONY : all
all:
	make ArrayStack 
	make DoubleArray 
	make LinkList
