ArrayStack:
	g++ -o ArrayStack.o ArrayStack.cpp

DoubleArray:
	g++ -o DoubleArrayStack.o DoubleArrayStack.cpp

LinkList:
	g++ -o LinkListStack.o LinkListStack.cpp


.PHONY : all
all:
	make ArrayStack 
	make DoubleArray 
	make LinkList
